name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
      - name: Install meson dependencies
        run: |
          python -m pip install scikit-build   

      - name: Add H8L ppa
        run: |
          sudo apt-get install --assume-yes software-properties-common
          sudo add-apt-repository ppa:hwangsaeul/nightly
          sudo apt-get update

      - name: Install package dependencies
        run: |
          sudo apt-get install --assume-yes \
                  libsoup2.4-dev \
                  libsrt-dev \
                  libjson-glib-dev \
                  libgstreamer-plugins-bad1.0-dev \
                  libgaeguli-dev gaeguli-tools \
                  libhwangsae-dev libhwangsae-test-common-dev \
                  meson ninja-build

      - name: Compile
        run: |
          meson build
          ninja -C build 
